### ISSUE TITLE
Stopping incremental search should deselect

### ISSUE THREAD

**Issue by m27315** [whitphx/vscode-emacs-mcx#105]
Steps to reproduce:

1. Perform incremental search (C-s).
2. After finding a match, exit/cancel search (C-g).
3. Begin typing.  :smile: Because last search is selected, it will be unexpectedly deleted and replaced with what you are typing now.

This requires extra C-g to deselect, which is different than Emacs.  (It does not automatically select searches.  It merely highlights them.)

It's a small thing, but I frequently type over the very thing I was searching, which I then have to first realize, then calm down, then undo, and then do whatever I really wanted.  :smile:  It's an minor annoyance that makes me want to switch back to Emacs.

Thanks for the great plug-in.  It's my favorite!

**Comment by tuttieee** [comment]
Thank you for the suggestion and sorry for my late response.

I understand. I will implement it.
However, there might be some discussions about whether it is better to simulate a strictly emacs-like behavior for the majority of the users.
So then, I plan to make it switchable between the original VSCode's behavior and the emacs-like behavior you suggested in this issue.
(Related to https://github.com/tuttieee/vscode-emacs-mcx/issues/113#issuecomment-494030719 )

Please let me know any opinions if you have.

And I will work on other issues of course.
Thanks!

**Comment by m27315** [comment]
Thanks for your openness to suggestion.  I'm sorry for my even later response.  :smile: 

Personally, I would prefer a strictly Emacs like behavior; otherwise, I would adapt to VScode's native bindings.  However, I can see a use-case for both, and I can understand your desire to please both camps.  If it was switchable, I think everyone should be pleased.

Thanks again for considering my suggestion.

**Comment by whitphx** [comment]
Resolved via #666
