### ISSUE TITLE
[Q] C-e(move-end-of-line) behavior.

### ISSUE THREAD

**Issue by hiroyuki-sato** [whitphx/vscode-emacs-mcx#1099]
Hello, thank you for developing this extension.
I have a question about `C-e`(move-end-of-line) behavior.

Is it possible `move-end-of-line` move to the end of the line instead of the window end?(move-beginning-of-line too)

For example, current cursor points to the head of `move-end-of-line`.

I expect move-end-of-line move to after `)`.
But It moves to after `end of`

* VScode: 1.62
* Awsome Emacs Keymaps: v0.36.3

Best regards.

<img width="438" alt="emacs" src="https://user-images.githubusercontent.com/767650/140515927-8f3d4589-1415-4148-823a-317f478fc929.png">

`C-e` を押すと、行の末尾でなく、ウインドウの右端に移動してしまうのですがこれを行末に移動するように変更することは可能でしょうか？(似たIssueを探しましたが見つけられなかったため質問いたしました)

よろしくお願いします。

**Comment by whitphx** [comment]
It is currently not supported.
This issue will be kept open as a task ticket.
Thank you for the post.

**Comment by whitphx** [comment]
`C-a` has already been fixed in #123, but it is still different from the original behavior.

**Comment by hiroyuki-sato** [comment]
Hello, @whitphx. Thank you for your reply. I'll wait that feature.

**Comment by whitphx** [comment]
Released in 0.36.4

**Comment by hiroyuki-sato** [comment]
Thank you for improving the code. v0.36.5 worked as I expected!!
