### ISSUE TITLE
C-m as RET

### ISSUE THREAD

**Issue by dwellmind** [whitphx/vscode-emacs-mcx#1137]
C-m should be same as RET (see https://www.gnu.org/software/emacs/manual/html_node/efaq/Basic-keys.html).

Same as C-i as Tab #774.

**Comment by whitphx** [comment]
C-m is already working like the enter key.
What the problem?

**Comment by whitphx** [comment]
Do you mean assigning different new-line commands to C-j and C-m as below?
* C-j (newline-and-indent)
* C-m (newline)

**Comment by dwellmind** [comment]
I don't know if it is possible with VSCode, but I'd like `C-m` to be interpreted everywhere as `RET`. Maybe there is a generic solution for it? This can avoid users to bind keys like `C-m` to the `RET` behavior for each new use case.

I noticed that with the [edamagit plugin](https://github.com/kahole/edamagit). When I use `C-m` in the Magit Status interface (some problem with `C-i`), it does nothing.

**Comment by whitphx** [comment]
I see, but from my understanding, there is no general way to make `C-m` to work same as `enter` (RET) on VSCode.
To do it , we have to individually assign `C-m` to an appropriate command in each case.

For example, Awesome Emacs Keymap specifically assigns `C-m` on the command palette to work same as `enter` as below:
https://github.com/whitphx/vscode-emacs-mcx/blob/9af5c1b25b9b9c9c353d6c1e72b2b56ee99470cf/keybindings.json#L846-L850

However, not all the VSCode UIs provide injectable commands so I think `C-m` cannot cover all the cases.
If you can list up the situations where you want to use `C-m` as RET, I can check each and assign `C-m` for possible ones.

As for Edamagit, they should assign `C-m` for their commands by themselves.

**Comment by dwellmind** [comment]
If I understand well, there is multiple solutions for cases like Magit Status:

- let users add keybinding themselves
- make a PR in `vscode-emacs-mcx` to add keybindings
- make a PR in `edamagit` to add keybindings

What do you think about it?

**Comment by whitphx** [comment]
Well, so you are thinking only of plugin-specific keybindings on Edamagit and do not have any problems on VSCode's general UIs?
Then, it's not this plugin's responsibility and you should define your own keybindings on your local or create a PR with them to Edamagit repo.
