### ISSUE TITLE
Extended version of executeCommand() with prefixArgument

### ISSUE THREAD

**Issue by whitphx** [whitphx/vscode-emacs-mcx#1146]
Ref: https://github.com/whitphx/vscode-emacs-mcx/issues/1127#issuecomment-997157436

To call arbitrary commands with prefix argument, this extension should provide its own `executeCommand()`.

The command name is like `emacs-mcx.executeCommandWithPrefixArgument()`?

API design plan:
```typescript
vscode.commands.executeCommand("emacs-mcx.executeCommand", { command: "<commandName>", args: {...} })
vscode.commands.executeCommand("emacs-mcx.executeCommand", ["<commandName>", {...} ])
```
will call `<commandName>` command with arguments `{ ...args, prefixArgument }`.

The key name `prefixArgument` can be customizable with the third argument of `emacs-mcx.executeCommand()`

**Comment by whitphx** [comment]
@tshino Hi, I created a prototype of the command `emacs-mcx.executeCommandWithPrefixArgument` in #1150, though which you can call another command with the prefix argument.
For example, if you define the keybinding below,
```json
      {
        "key": "ctrl+x e",
        "command": "emacs-mcx.executeCommandWithPrefixArgument",
        "args": {
          "command": "kb-macro.playback",
          "prefixArgumentKey": "repeat"
        }
      }
```
`C-u C-x e` will execute `kb-macro.playback` with the argument `{ repeat: 4 }`.

Does it satisfy your needs? Can you give some comments, suggestions, or any ideas on it?

**Comment by tshino** [comment]
@whitphx Thank you so much. The API design looks perfect for my use case!

But I found one problem with the implementation at 0d4db90.
I recorded the following sequence.
```
C-f C-n
```
And triggered playback of the sequence by `C-u C-x e` with the keybinding you described.
Then the cursor moved as if I typed:
```
C-f C-f C-f C-f C-n
C-f C-n
C-f C-n
C-f C-n
```
I think the prefix argument was applied twice.
One was to the proxy and the other was to the first call of `emacs-mcx.forwardChar`.

**Comment by whitphx** [comment]
@tshino Thank you, good catch!
The prefix argument has not been cleared before calling the target command with the current implementation.
I updated the PR, so can you please try it out again?

**Comment by tshino** [comment]
@whitphx It works perfectly for me!

After this new command has been shipped successfully with your extension, I will update the keymap wrapper file on my extension to enable prefix-argument support.
To mitigate dependency risks, I will arrange the keybindings to use the `emacs-mcx.prefixArgumentExists` context to call the new `emacs-mcx.executeCommandWithPrefixArgument` command only when it is needed.

Thanks a lot!

**Comment by whitphx** [comment]
@tshino Thank you for the trial. I'm glad to hear it works good.

> To mitigate dependency risks, I will arrange the keybindings to use the emacs-mcx.prefixArgumentExists context to call the new emacs-mcx.executeCommandWithPrefixArgument command only when it is needed.

It makes sense 👌 

`emacs-mcx.executeCommandWithPrefixArgument` will be included in the next release.
