### ISSUE TITLE
Auto-completion

### ISSUE THREAD

**Issue by pors** [whitphx/vscode-emacs-mcx#1155]
Hi, love this extension!!

I'm quite new to VScode, so `M-/` is in my fingers, but that doesn't do anything. How do I get the functionality of Emacs style auto-completion in VScode?

**Comment by whitphx** [comment]
It should work like this.`alt+/` calls VSCode's intellisense (`alt` is the default meta key on macOS).
![emacs-mcx-intellisense](https://user-images.githubusercontent.com/3135397/148650235-e171d965-3b8c-44f4-91b5-3e7600abe85f.gif)

VSCode does not have Emacs-style autocomplete (Abbrev Expansion). This extension assigns `M-/` to the VSCode native intellisense instead.

**Comment by pors** [comment]
Yeah that does work for me as well. I like Abbrev Expansion better, but anyway, I'll get used to it. Thanks!
