### ISSUE TITLE
Key chord `C-x C-k` closes all windows, quite unexpected

### ISSUE THREAD

**Issue by jabielecki** [whitphx/vscode-emacs-mcx#1162]
## Intent

In VScode, I open one file for editing and then I open a second file in the same way. So there are two editors.

I want to close the current editor.

By "editor" I understand a tab, or in Emacs-ish a "buffer".

## What Happens

- When I edit a file and press `C-x C-k` it closes all editors.
- When I edit a file and press `C-x k` it closes just the current editor.

## Severity

Low, just an annoyance to suddenly lose all the windows.

## What I Expected Instead

I expected the vanilla Emacs logic, which seems to be:

- do not use `C-x C-k` for any high-impact action as it is very easy to mistype; in fact Emacs (27.1) uses it just as a prefix for kmacro:

```
Global Bindings Starting With C-x C-k:
key             binding
---             -------

C-x C-k C-a	kmacro-add-counter
C-x C-k C-c	kmacro-set-counter
C-x C-k C-d	kmacro-delete-ring-head
C-x C-k C-e	kmacro-edit-macro-repeat
C-x C-k C-f	kmacro-set-format
C-x C-k TAB	kmacro-insert-counter
C-x C-k C-k	kmacro-end-or-call-macro-repeat
C-x C-k C-l	kmacro-call-ring-2nd-repeat
C-x C-k RET	kmacro-edit-macro
C-x C-k C-n	kmacro-cycle-ring-next
C-x C-k C-p	kmacro-cycle-ring-previous
C-x C-k C-s	kmacro-start-macro
C-x C-k C-t	kmacro-swap-ring
C-x C-k C-v	kmacro-view-macro-repeat
C-x C-k SPC	kmacro-step-edit-macro
C-x C-k b	kmacro-bind-to-key
C-x C-k e	edit-kbd-macro
C-x C-k l	kmacro-edit-lossage
C-x C-k n	kmacro-name-last-macro
C-x C-k q	kbd-macro-query
C-x C-k r	apply-macro-to-region-lines
C-x C-k s	kmacro-start-macro
C-x C-k x	kmacro-to-register
```

Also while we're at it: in Doom Emacs without evil I use `C-c q F` chord and it closes all editor windows.
Could be also shortened to `C-c q`.

## Thank You

This software is the best VSCode Emacs plugin I could find, so a big thumbs up and five stars. :star: :star: :star: :star: :star:  I appreciate the maintenance work. Feel free to just drop this issue if it goes against some larger plan.

**Comment by whitphx** [comment]
Thank you for your kind description and message.
I will drop this keybinding.

TBH, I copied a large part of the keybindings from the Emacs Friendly Keymap extension at the very beginning of this extension and have not checked it very much, so probably there are unintended keybindings.
`C-x C-k` has actually been included in the copied keybindings as https://github.com/whitphx/vscode-emacs-mcx/commit/d1cc957399f16eb9c5ced455184481de91313f0d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R478-R479.
FYI, as long as I investigated the log, this keybinding has been introduced in the original extension with [this commit](https://github.com/SebastianZaha/vscode-emacs-friendly/commit/8e381a9835b45fcfec592fa984ed79b4dc867373), but I don't know the reason.

Please let me know if there are other useless or weird keybindings.
