### ISSUE TITLE
C+x 0 doesn't work in git diff mode

### ISSUE THREAD

**Issue by sickerin** [whitphx/vscode-emacs-mcx#1227]
`C+x 0` works fine in split editor mode. But in the git mode diff, it will work the first time (left to right, but not right to left).
Although the command `View: Focus Side in Active Editor` works for both cases.

**Comment by whitphx** [comment]
> `C+x 0 `

Are you talking about `C-x o` (Focus other split editor), not `C-x 0` (Close editors in the current group.)?

> in the git mode diff,

Are you talking about this diff view? https://code.visualstudio.com/Docs/editor/versioncontrol#_viewing-diffs
If not, please elaborate it. Screenshot attached is preferrable.

> the command `View: Focus Side in Active Editor`

Are you talking about `View: Focus Other Side in Active Editor`?
I checked the command name with VSCode 1.65.2. 

---

If all of them are YES, the answer would be
`C-x o` is switcher between the editors, but the split diff views are in the same editor so `C-x o` does not work as a switcher between them.
