### ISSUE TITLE
i-search (C-s) initialization

### ISSUE THREAD

**Issue by secodama** [whitphx/vscode-emacs-mcx#1278]
`i-search (C-s) is initialized with the currently selected string and the previous search is removed.`
https://github.com/whitphx/vscode-emacs-mcx#i-search-c-s-is-initialized-with-the-currently-selected-string-and-the-previous-search-is-removed

This behavior is not working now.
I could initialize i-search with selected string in previous version.
But I can't now.

**Comment by whitphx** [comment]
Thank you for the report.
It's been since v0.41.0.

I will consider about the fix, and please use the previous versions until the next release including the fix.
