### ISSUE TITLE
initial isearch issues

### ISSUE THREAD

**Issue by mizerlou** [whitphx/vscode-emacs-mcx#1279]
prior to version v0.41.0, i could start searching forward in a buffer by using "ctrl-s".  however, now, ctrl-s doesn't do anything until i use the standard vscode search "cmd-f".  while the search widget is showing, "ctrl-s" works normally.

v0.40.1 works fine, but version after that exhibit the behavior described above.

**Comment by whitphx** [comment]
Thank you for the report.
Can you provide the info about your environment, e.g. OS, VSCode version, etc.?

**Comment by mizerlou** [comment]
Version: 1.61.2 (Universal)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z (5 mos ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.4.0

**Comment by whitphx** [comment]
Dev note:

Options with v1.63.0:
https://github.com/microsoft/vscode/blob/1498d0f34053f854e75e1364adaca6f99e43de08/src/vs/editor/contrib/find/browser/findController.ts#L588-L600

in v1.66.2:
https://github.com/microsoft/vscode/blob/dfd34e8260c270da74b5c2d86d61aee4b6d56977/src/vs/editor/contrib/find/browser/findController.ts#L588-L600
