### ISSUE TITLE
Incorrect behavior when setting mark and searching

### ISSUE THREAD

**Issue by furious-luke** [whitphx/vscode-emacs-mcx#1328]
Hi there, thanks for all the hard work on this extension, it's much appreciated!

I'm encountering an issue when trying to select regions of text over long ranges. Normally, I would set the mark at the beginning of the region I'm interested in selecting with `CTRL+SPC`, and then I would search to the position I'm interested in ending the region. So, I would do something like `CTRL+S` then type a short phrase to indicate the ending position. Then, I could perform an operation, like `CTRL+W`.

However, I'm noticing that in the above steps, when I hit `CTRL+S` my selection terminates. I believe the correct Emacs behavior is to maintain the selection over the search.

**Comment by dbikel** [comment]
Hi, @furious-luke .  Do you find that CTRL+S works at all?  I'm finding that it doesn't do anything, esp. when I unbind it for the native "Find" command and just have it bound to `emacs-mcx.isearchForward`.

**Comment by whitphx** [comment]
Thank you for the detailed description.
That's right, the current C-s behavior with mark-mode is not emulating the original one. I will work on it.

**Comment by furious-luke** [comment]
Hey @dbikel! Yep, `CTRL+S` works for me straight out of the box.

@whitphx Awesome, thanks so much!

**Comment by dbikel** [comment]
Okay, that's great, but is it true incremental search, or just a different
keystroke to invoke the native Find command widget?

**Comment by furious-luke** [comment]
@dbikel It's incremental search. It behaves very similarly to Emacs, except for the issue stated in my first post.

**Comment by whitphx** [comment]
Fixed with 0.51.2 👍

**Comment by van-latimer-rr** [comment]
Works like a charm.
