### ISSUE TITLE
How to insert a hash (aka pound in the US) character when using a UK keyboard on MacOS?

### ISSUE THREAD

**Issue by nickglazzard1959** [whitphx/vscode-emacs-mcx#1345]
The Macbook Pro UK keyboard has a single key that shares "3", the UK pound currency symbol, £, (with shift) and the hash (sometimes called pound in the US, I believe) symbol, #, (with alt). In Emacs, the following Lisp code makes alt-3 insert a hash character: (define-key key-translation-map (kbd "M-3") (kbd "#"))

So far, I haven't found any way to insert a hash character using this extension in VS Code on MacOS with a UK keyboard. I hope there is something I've overlooked, because the extension is very nice, but this is a bit of a showstopper! (Well, I can cut and paste an existing hash character, but ... :-) ).

**Comment by nickglazzard1959** [comment]
OK, so adding this to keybindings.json will allow hashes to be entered with (shift)+3 ... I don't need the UK pound sign anyway.
```
[
    {
        "key": "shift+3",
        "command": "type",
        "args": {
            "text": "#"
        }
    }
]
```

**Comment by aramirezreyes** [comment]
Also found this. I think the issue deserves to remain open as the hack may not be useful for anyone requiring the UK pound sign at some point!)
