### ISSUE TITLE
Mark-mode becomes buggy when the same document is opened in multiple editors

### ISSUE THREAD

**Issue by whitphx** [whitphx/vscode-emacs-mcx#1457]
Because the mark-mode state is managed based on the document, not the editor.

**Comment by whitphx** [comment]
Background of the `EditorIdentity` based on the document:

* Where `EditorIdentity` has been introduced: https://github.com/VSCodeVim/Vim/pull/399
  * Primitive implementation of the map from `EditorIdentity` to `ModeHandler`: https://github.com/VSCodeVim/Vim/pull/399/files#diff-7cbd40a729b9fdb8ef7c1ed96d61b766cf1b30e8ba756e6a300fecdd11cb6466R51

**Comment by hidaris** [comment]
Hi, is it possible for this problem to be solved?

**Comment by whitphx** [comment]
To emulate the Emacs behavior, the mark-mode status and the anchors should be synced across editors on the same document.
This also works well with VSCode Extension API where there is no API to track each `TextEditor` object's lifecycle.
