### ISSUE TITLE
Up and Down Arrow when expression overrides Jupyter Notebook arrow key bindings

### ISSUE THREAD

**Issue by kchang718** [whitphx/vscode-emacs-mcx#1466]
The default when expression `editorTextFocus` interacts with *Notebook: Focus Next Cell Editor*.  If changed to `editorTextFocus && !notebookEditorFocused`, things work as expected.

![image](https://user-images.githubusercontent.com/76565293/202189484-c02ef23a-afd5-4b44-bc99-bfabf4084c4d.png)

**Comment by whitphx** [comment]
I could not understand what was the problem with the original keybinding where the up and down keys work as the Emacs commands on Jupyter cells.
Can you elaborate it?

**Comment by kchang718** [comment]
Whatever was done with Jupyter Notebooks or with vscode, but at this moment, emacs keys works properly with default settings in the notebook.  Thanks for the attention.

**Comment by kchang718** [comment]
Whatever was done with Jupyter Notebooks or with vscode, but at this moment, emacs keys works properly with default settings in the notebook. Thanks for the attention.
