### ISSUE TITLE
Any chance we will get a full implementation of elisp in this extension at some point?

### ISSUE THREAD

**Issue by gtusr** [whitphx/vscode-emacs-mcx#1477]
This could make it a lot easier to port over additional packages.  

The computer algebra system Mathematica enforces a clean split between "kernel" and "front-end."  Unfortunately, this is not the case yet for emacs because otherwise it would be a much easier to integrate emacs functionality in other editing environments.      

For reference: [make yourself a lisp](https://github.com/kanaka/mal) ... in almost a hundred different languages.

**Comment by whitphx** [comment]
There is no plan to do it with this extension as it is not designed in that manner.
While it is interesting to implement Lisp runtime and bridge the VSCode API to it, I think it will be done as another extension.
