### ISSUE TITLE
Exiting mark mode

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [whitphx/vscode-emacs-mcx#149]
I know of the following command IDs:
*  `emacs-mcx.setMarkCommand`: To set mark
* `cancelSelection`: To cancel a given selection

Is there a command ID to leave mark mode? (a command ID that exists this when condition: `emacs-mcx.inMarkMode`?)

I mention this because if I notice using `cancelSelection` doesn't seem to be enough to actually exit `MarkMode`

**Comment by amelio-vazquez-reina** [comment]
Is the answer here? https://github.com/tuttieee/vscode-emacs-mcx/pull/31/files

i.e. to use `emacs-mcx.cancel`?

**Comment by tuttieee** [comment]
Partially yes: `emacs-mcx.cancel` works like [this](https://github.com/tuttieee/vscode-emacs-mcx/blob/16ab3ad6363294f7e112d21717241fb882b79772/src/emulator.ts#L192-L212)

It stops mark-mode, but also has other effects like stopping multi-cursor etc based on the editor state, as this behavior is comfortable for `C-g` keybinding.

And currently there is no command which only triggers "exit mark-mode".

**Comment by tuttieee** [comment]
What kind of command do you need, or just `emacs-mcx.cancel` is enough?
* Only turn off the internal mark-mode flag, which preserves the selections but prevent from expanding the selections at succeeding move commands.
* In addition, unset the selections.
