### ISSUE TITLE
Jumping to matching brace/bracket/paren exits mark mode

### ISSUE THREAD

**Issue by zpencer** [whitphx/vscode-emacs-mcx#1515]
In Emacs, if the cursor is on any of these characters `() {} []`, then it's possible to jump to the matching character with `forward-sexp` or `backward-sexp`. If mark mode is activated, then the entire region of text is selected.

In vscode, the closest equivalent is "Go to Bracket" `editor.action.jumpToBracket`.

With this extension, when mark mode is enabled, "Go to Bracket" will jump to the matching character, but mark mode exits (nothing is selected).

I suspect we need to create something similar to this extension's `ForwardParagraph` and `BackwardParaph` commands, which *do* work correctly with mark mode. I notice there are keymap commands like `emacs-cx.paredit.forwardSexp` but I can't seem to make them work.

The "Select to bracket" is a workaround but it doesn't behave like emacs.

**Comment by zpencer** [comment]
When I hit the keys bound to `emacs-mcx.paredit.forwardSexp`, nothing happens. This is the case whether or not I'm setting a mark. Not sure if this is expected. Is there a log I can check? (Sorry I am not very experienced with how to debug vscode.)

**Comment by whitphx** [comment]
I think you should check if `emacs-mcx.paredit.forwardSexp` is working correctly.
It should work as below:
![CleanShot 2023-02-17 at 01 02 50](https://user-images.githubusercontent.com/3135397/219421085-44607bb9-01b9-4c03-b27f-d9aaf7c06775.gif)

You can see the logs in the developer tools (select "Developer: Toggle Developer Tools" from the command pallete).
The log level of this extension can be controlled via the `emacs-mcx.debug.loggingLevelForConsole` setting.
