### ISSUE TITLE
Map capslock to ctrl

### ISSUE THREAD

**Issue by van-latimer-rr** [whitphx/vscode-emacs-mcx#1538]
Thank you very much for this extension. It is a big part of my workflow!

Is it possible to use map caps lock to control in the extension? Ie, I would like to be able to use `capslock+A` in place of `ctrl+a`.

**Comment by whitphx** [comment]
I think most people have done it at the OS level, e.g. at least I did it on macOS and Ubuntu.
Is it necessary to do it with this extension?

**Comment by van-latimer-radialrad** [comment]
It would be difficult in my circumstance; I am on a computer on which I have limited access to the OS, and I have to work on multiple computers.

**Comment by whitphx** [comment]
Seems like it's not possible: https://github.com/microsoft/vscode/issues/13312
(assigning `capslock` to a command is possible, but the Capslock key continues working as a Capslock toggle. Also, combination keybindings such as `capslock+f` doesn't work.)
