### ISSUE TITLE
The corresponding Emacs keymap configuration file?

### ISSUE THREAD

**Issue by suntong** [whitphx/vscode-emacs-mcx#1555]
Hi, 

Of all the key combinations available-in/defined-by this package, do we have the corresponding Emacs keymap configuration file as well? 

I'd assume that everything is by default, but 

- Some useful Emacs packages don't define key mapping themselves, and we need to define them on our own in our file, like `redo` etc.
- Some functions, like toggle commenting (toggle the selected lines as or off comments), have multiple key mappings, 
- Some key mapping I found here, like `C-M-n` & `C-M-p`, _"Add selection to next/previous find match"_, I've never known exist in Emacs before (and after trying, doesn't work in my Emacs)

All in all, I know the [vscode-emacs-mcx](https://github.com/whitphx/vscode-emacs-mcx) is to make vscode works like Emacs, but I want an easy way for my Emacs' key mapping/function behave exactly as vscode-emacs-mcx as well. How can I do that? Thx!

**Comment by kshartman** [comment]
Look in the code - package.json around line 373 configuration key "keybindings": all the commands it binds are there.  For any vscode extension, you add the relevant section to package.json contributes section in a declarative manner. vscode generates the keybindings, settings, etc from the information in your package.json.

**Comment by suntong** [comment]
> Look in the code - package.json around line 373 configuration key "keybindings"

which looks something like this:
https://github.com/whitphx/vscode-emacs-mcx/blob/701c69a642d14800aa472bfd86f5845774563604/package.json#L373-L394

IE, I know all the commands it binds are there, yet there are for  vscode but not emacs.

Whereas 
> I want an easy way for my Emacs' key mapping/function behave exactly as vscode-emacs-mcx

IE, what I was asking for was,

> do we have the corresponding Emacs keymap configuration file as well?

**Comment by kshartman** [comment]
https://www.gnu.org/software/emacs/refcards/pdf/refcard.pdf

**Comment by suntong** [comment]
> there is no way to transfer an arbitrary Emacs command to VSCode...
> There's no direct translation from Emacs commands to VSCode's.

That, actually, is _not_ what I'm asking, as I know it is impossible.

what I was asking for was,

> do we have the corresponding Emacs keymap configuration file as well?

So let me ask in another way, and maybe this time it is more clearer.

I assume that people use Emacs key-combination for VSCode because either

-  A, they use Emacs before, and they feel comfortable with their  Emacs keymap configurations, or
- B, they'll still using Emacs (like in their Linux machines) parallel to using VSCode

Either way, they'd have a keymap configurations file, defining what hotkeys do what, and they'd normally configure the hotkeys in Emacs and VSCode to be the same. Else, it'll be more confusing when switching between the two.

This mapping of what hotkeys do what in Emacs is what I has been asking.

**Comment by whitphx** [comment]
No, there is no shared file.
Emacs defines the keymap in elisp, and VSCode does via `package.json`, and there is no translator.

**Comment by kshartman** [comment]
> This extension just implements and defines some of the default keybindings of Emacs. Emacs users who customized their elisp so much have to customize `package.json` in VSCode as well to reproduce their customized keybindings.

That is not strictly true.  Package developers (or tweakers) change default bindings in package.json but users do it in keybindings.json (File -> Preferences -> Keyboard).  For example, mine refers to commands in this (great!) package,  also some in "awesome emacs keymap" and some in extensions I wrote for myself.  You can even override the package developers choices.  I can almost use Visual Studio code with pure emacs muscle memory now.

**Comment by suntong** [comment]
Ah~~~, finally someone who I had been expecting shows up:

> I assume that people use Emacs key-combination for VSCode because either
> 
> * A, they use Emacs before, and they feel comfortable with their  Emacs keymap configurations, or
> * B, they'll still using Emacs (like in their Linux machines) parallel to using VSCode
> 
> Either way, they'd have a keymap configurations file, defining what hotkeys do what, and they'd normally configure the hotkeys in Emacs and VSCode to be the same. Else, it'll be more confusing when switching between the two.

@kshartman, would it be possible that you share your Emacs keybinding setting file please?

E.g., my _whole_ Emacs setting is published/available at https://github.com/suntong/emacs.d

Thanks
