### ISSUE TITLE
Keep search bar focus and not to exit when editing search pattern

### ISSUE THREAD

**Issue by zero00072** [whitphx/vscode-emacs-mcx#1607]
Type: UX

Problem:
When I want search, I press `C-s`, or `M-x replace RET` to open search bar. But problem occurred when I want edit search bar with LEFT key, RIGHT key, HOME key and END key. It direct move cursor on edit area and closed the search bar. My behaviour is wishing it not to close the search bar.

I added this to my keybindings.json:

```json
[
  {
    "key": "right",
    "command": "-emacs-mcx.isearchExit",
    "when": "editorFocus && findWidgetVisible && !config.emacs-mcx.cursorMoveOnFindWidget && !isComposing && !replaceInputFocussed"
  },
  {
    "key": "left",
    "command": "-emacs-mcx.isearchExit",
    "when": "editorFocus && findWidgetVisible && !config.emacs-mcx.cursorMoveOnFindWidget && !isComposing && !replaceInputFocussed"
  },
  {
    "key": "home",
    "command": "-emacs-mcx.isearchExit",
    "when": "editorFocus && findWidgetVisible && !config.emacs-mcx.cursorMoveOnFindWidget && !isComposing && !replaceInputFocussed"
  },
  {
    "key": "end",
    "command": "-emacs-mcx.isearchExit",
    "when": "editorFocus && findWidgetVisible && !config.emacs-mcx.cursorMoveOnFindWidget && !isComposing && !replaceInputFocussed"
  }
]
```

I can customize it by myself. But I think this may be an UX improving.

**Comment by whitphx** [comment]
https://github.com/whitphx/vscode-emacs-mcx#the-cursor-cannot-be-moved-on-the-find-widget-as-the-widget-closes-with-movement-keys

**Comment by zero00072** [comment]
The mode is not good enough. If I type C-n & C-p, I am not meaning "Crate a new file" & "Move to the file", It should do plain origin Emacs "Next line and close search", "Previous line and close search".

Never "Crate a new file" & "Move to the file" in any.
