### ISSUE TITLE
Editor moves back to cursor position after it's revealed from background

### ISSUE THREAD

**Issue by cobaltmagnet** [whitphx/vscode-emacs-mcx#1714]
![aek_why](https://github.com/whitphx/vscode-emacs-mcx/assets/148535763/96b6a581-b77f-465b-b6a5-6719fa358997)
Same as title. Without the extension it keeps where it's supposed to be but as soon as it's installed, the editor jumps back to the cursor position when it's hid and revealed. I guess it started recently. I prefer the normal behavior.

Thank you though for the tough work for making such a nice extension.

**Comment by whitphx** [comment]
This should be fixed in the next release. Please check it, thanks!
