### ISSUE TITLE
I have a question about MessageManager.showMessage()

### ISSUE THREAD

**Issue by DrScKAWAMOTO** [whitphx/vscode-emacs-mcx#1782]
Hi,
I am developping the non-incremental-search feature, such as search-forward command, of emacs.
This feature will provide a convenient cursor movement in the find widget ( https://github.com/whitphx/vscode-emacs-mcx/issues/137 [).](https://github.com/whitphx/vscode-emacs-mcx/issues/137) 

So I have a question about MessageManager.showMessage().
How I see the output of MessageManager.showMessage() ?

Thanx.

**Comment by whitphx** [comment]
Hi, good to know you are doing an amazing stuff!

The message is simply displayed on the status bar.
For example, when you type `C-SPC` to set the mark, the message is shown like this:
![CleanShot 2023-12-04 at 11 49 32@2x](https://github.com/whitphx/vscode-emacs-mcx/assets/3135397/c853837b-8886-4da2-b2cf-3737fd847484)

**Comment by DrScKAWAMOTO** [comment]
Thank you for your advice.
