### ISSUE TITLE
Thinking about replacing the original text search with the new quick search

### ISSUE THREAD

**Issue by hidaris** [whitphx/vscode-emacs-mcx#1843]
I found that the new quick search function of vscode is very easy to use. Compared with the original search function, it also supports emacs shortcut keys to switch up and down. Would you like to consider it?  

@command:workbench.action.experimental.quickTextSearch

https://github.com/whitphx/vscode-emacs-mcx/assets/8336146/c7ab2363-1ead-47b5-a7d7-0671fcb74e71

**Comment by andyleejordan** [comment]
Oo, nice. I bound this to `M-s o` for myself (it's just like Occur)!

**Comment by whitphx** [comment]
Thank you @hidaris , I didn't know this feature, and agree to adding it as @andyleejordan 's solution where it's assigned to `M-s o` like Occur.
