### ISSUE TITLE
default keybindings for special characters are "unknown"

### ISSUE THREAD

**Issue by aldrichtr** [whitphx/vscode-emacs-mcx#1867]
vscode version: 1.85.1
Awesome Emacs Keymap extension version: 0.58.0

`emacs-mcx.copyToRegister`, `emacs-mcx.insertRegister`, and `emacs-mcx.typeChar` show several keybindings as "unknown". 

for example, table below.  Also, if you open the "default keybindings" these bindings show as "unknown" there as well.

| ID                       | Description | Default |
|--------------------------|-------------|---------|
| emacs-mcx.copyToRegister |             | unknown |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | '       |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | ,       |
|                          |             |         |
|                          |             | -       |
|                          |             |         |
|                          |             | .       |
|                          |             | /       |
|                          |             | 0       |
|                          |             | 1       |
|                          |             | 2       |
|                          |             | 3       |
|                          |             | 4       |
|                          |             | 5       |
|                          |             | 6       |
|                          |             | 7       |
|                          |             | 8       |
|                          |             | 9       |
|                          |             | unknown |
|                          |             | ;       |
|                          |             | unknown |
|                          |             | =       |
|                          |             |         |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | A       |
|                          |             | B       |
|                          |             | C       |
|                          |             | D       |
|                          |             | E       |
|                          |             | F       |
|                          |             | G       |
|                          |             | H       |
|                          |             | I       |
|                          |             | J       |
|                          |             | K       |
|                          |             | L       |
|                          |             | M       |
|                          |             | N       |
|                          |             | O       |
|                          |             | P       |
|                          |             | Q       |
|                          |             | R       |
|                          |             | S       |
|                          |             | T       |
|                          |             | U       |
|                          |             | V       |
|                          |             | W       |
|                          |             | X       |
|                          |             | Y       |
|                          |             | Z       |
|                          |             | [       |
|                          |             | \       |
|                          |             | ]       |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | `       |
|                          |             | A       |
|                          |             | B       |
|                          |             | C       |
|                          |             | D       |
|                          |             | E       |
|                          |             | F       |
|                          |             | G       |
|                          |             | H       |
|                          |             | I       |
|                          |             | J       |
|                          |             | K       |
|                          |             | L       |
|                          |             | M       |
|                          |             | N       |
|                          |             | O       |
|                          |             | P       |
|                          |             | Q       |
|                          |             | R       |
|                          |             | S       |
|                          |             | T       |
|                          |             | U       |
|                          |             | V       |
|                          |             | W       |
|                          |             | X       |
|                          |             | Y       |
|                          |             | Z       |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | unknown |
|                          |             | unknown |

**Comment by whitphx** [comment]
Thank you for reporting it!
