### ISSUE TITLE
VScode search is broken

### ISSUE THREAD

**Issue by hermannsorgel** [whitphx/vscode-emacs-mcx#1929]
Hi, Yuichiro! Thanks for your time and work!
Here what we have:

**How to Reproduce:**
1. Open 'Search Menu' with `Opt + Cmd+ F`
2. Type anything
3. Press any arrow key

**Problem:** pressing arrow will close 'Search Menu'.

If I disable Awesome Emacs Keymap everything works as usual

[Video](https://drive.proton.me/urls/SASBA1EX30#36JUrTFuNs93)

**Comment by whitphx** [comment]
Hi,
plz refer to https://github.com/whitphx/vscode-emacs-mcx?tab=readme-ov-file#the-cursor-cannot-be-moved-on-the-find-widget-as-the-widget-closes-with-movement-keys
