### ISSUE TITLE
Backspace broken in `ipynb` and interactive windows

### ISSUE THREAD

**Issue by regob** [whitphx/vscode-emacs-mcx#2113]
Hi!

Backward char deletion (`backspace`) jumps back to the front of the line in `.ipynb` and `interactive window`. 
# Repro:
Create an ipynb notebook or interactive window and delete a char. *Before backspace*: (| is where my cursor at)
```python
import sys
import os|
```
*After backspace*:
```python
import sys
|import o
```

I bisected the issue and it seems 2c587e88cf0550d7c118441c2c4499127f8c15b6 introduced the bug, and `v0.62.2` works fine. (Edit: Not 100% sure about the bisect, because the issue is a bit non-deterministic.)

Only happens when ` emacs-mcx.strictEmacsMove`  is `true` in my config. And it happens for multiple commands:
- `deleteLeft`
- `deleteWordLeft`
-  `emacs-mcx.deleteBackwardChar`

**Comment by chee** [comment]
this is also happening for me in markdown files.

**Comment by whitphx** [comment]
Thank you for the report! This should be fixed in 0.62.4.
Please reopen the issue if you still have the problem.
