### ISSUE TITLE
strange behaviour during inputing Japanese

### ISSUE THREAD

**Issue by te-sh** [whitphx/vscode-emacs-mcx#2120]
https://github.com/user-attachments/assets/4587575e-2c52-43c7-9a76-d20451a4d84f

I face strange behavior during inputting Japanese.

Sometimes cursor moves to start of the line unintentionally.
And sometimes part of inputted string copied to start of the line.

See my captured video.

**Comment by whitphx** [comment]
Thank you for the report! This should be fixed in 0.62.4.
Please reopen the issue if you still have the problem.
