### ISSUE TITLE
cursor jump to where fold exists

### ISSUE THREAD

**Issue by mmorinag127** [whitphx/vscode-emacs-mcx#2127]
Dear developers,

I need help with the following problem.
If there is a folded section somewhere in the code, the cursor jumps to the folded section when I delete a line or insert a new line.
This started happening with the latest update.

**Comment by Yikes2000** [comment]
Yes, very annoying.

Downgraded to v62.2 for the time being.

**Comment by whitphx** [comment]
Thank you for the report! This should be fixed in the next release, v0.62.5.
Please let me know or reopen this issue if the problem still exists.
