### ISSUE TITLE
Rectangles

### ISSUE THREAD

**Issue by pasha-bolokhov** [whitphx/vscode-emacs-mcx#278]
GNU Emacs has the following keys for manipulating rectangles:
copy rectangle to register C-x r r
kill rectangle C-x r k
yank rectangle C-x r y
open rectangle, shifting text right C-x r o
blank out rectangle C-x r c
prefix each line with a string C-x r t

I find many of them very useful, especially prefix one, sometimes kill/yank

XEmacs used to have better keybindings than GNU Emacs, but unfortunately the project is no longer alive, so we have to use whatever is left — GNU Emacs.
The main reason is Microsoft and Windows users, who grew up in Windows and used older and newer IDEs (starting with dummest Borland's Turbo Vision, and then IDEA, then... you know what), the authors of which had no exposure to readline or Emacs. Even though all of them *do* use readline in "bash", "mysql" and other command-line tools almost everyday (more so now because of "git", "npm", "yarn", "ng", and what not). To me it's like someone who had learned how to operate a chainsaw was asked to create a piano. They did create a piano, or what they thought a piano was

**Comment by tuttieee** [comment]
memo: https://www.atmarkit.co.jp/ait/articles/1805/11/news022.html

**Comment by whitphx** [comment]
Assigning sequence of individual character keys (without modifiers) is not supported by VSCode yet: https://github.com/microsoft/vscode/issues/48129

Implementing these commands is possible, but we have difficulty at assigning keys to the commands.

**Comment by whitphx** [comment]
Some of the commands are added in v0.32.0

**Comment by sdsmith** [comment]
Hey @whitphx , thank you for working on this. 

Are there any plans for adding `C-x r t`? It would be nice to have multi-line editing.

**Comment by whitphx** [comment]
Hi, yes, it will be, though I can't promise the date.

**Comment by whitphx** [comment]
I implemented `C-x r t` and it is released in v0.36.0, while it does not fully emulate the original behavior.
Please leave comments if there is some functionality you want to be implemented additionally.

**Comment by eriegz** [comment]
> I implemented `C-x r t` and it is released in v0.36.0, while it does not fully emulate the original behavior. Please leave comments if there is some functionality you want to be implemented additionally.

Just wanted to say thanks for this great extension, and for your continual improvements! :)

**Comment by whitphx** [comment]
I close this issue at this moment as it looks like the current implementation of these commands cover the demands enough.

Please reopen this issue of create a new one if you find something to be improved or added.
