### ISSUE TITLE
A way to return to the start position after search or yank

### ISSUE THREAD

**Issue by tmlgh** [whitphx/vscode-emacs-mcx#378]
Emacs sets the mark implicitly at the start position in a long-distance movement such as search and yank (also M->, but sorry I do not know the details of implicit marks). Thanks to this, we can return to the start position by using c-x c-x (or c-u c-space).

This is extremely convenient, but it has never been possible with other emacs key bindings in VSCode. (I also tried several bookmark extensions).

Now, it has become possible to do this in the latest version. This is not an issue, but I would like to share the method.

1. Install [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command)
2. Write the following in settings.json
```
"multiCommand.commands": [
    {
        "command": "multicmd.emacs-mcx.setMarkAndYank",
        "sequence": [
            "emacs-mcx.setMarkCommand",
            "emacs-mcx.setMarkCommand",
            "emacs-mcx.yank"
        ]
    },
    {
        "command": "multicmd.emacs-mcx.setMarkAndSearch",
        "sequence": [
            "emacs-mcx.setMarkCommand",
            "emacs-mcx.setMarkCommand",
            "emacs-mcx.isearchForward"
        ]
    },
    {
        // [Optional] Exchange the point and mark without the region
        "command": "multicmd.emacs-mcx.exchangePointAndMarkAndCancel",
        "sequence": [
            "emacs-mcx.exchangePointAndMark",
            "emacs-mcx.cancel"
        ]
    },
]
```
3. Write the following in keybindings.json
```
{
    "key": "ctrl+y",
    "command": "-emacs-mcx.yank",
    "when": "editorTextFocus && !editorReadonly"
},
{
    "key": "ctrl+y",
    "command": "multicmd.emacs-mcx.setMarkAndYank",
    "when": "editorTextFocus && !editorReadonly"
},
{
    "key": "ctrl+s",
    "command": "-emacs-mcx.isearchForward",
    "when": "!findWidgetVisible"
},
{
    "key": "ctrl+s",
    "command": "multicmd.emacs-mcx.setMarkAndSearch",
    "when": "!findWidgetVisible"
},
{
    "key": "ctrl+x ctrl+x",
    "command": "-emacs-mcx.exchangePointAndMark",
    "when": "editorTextFocus"
},
{
    "key": "ctrl+x ctrl+x",
    "command": "multicmd.emacs-mcx.exchangePointAndMarkAndCancel",
    "when": "editorTextFocus"
}
```
Enjoy!

**Comment by kshartman** [comment]
Awesome!  Solved a problem of mine too.  You can implement killSexp

// settings.json:
 {
            // [Optional] Kill Next Sexp
            "command": "multicmd.emacs-mcx.killSexp",
            "sequence": [
                "emacs-mcx.setMarkCommand",
                "emacs-mcx.paredit.forwardSexp",
                "emacs-mcx.killRegion"
            ]
}

// keybindings.json
{
        "key": "ctrl+alt+k",
        "command": "multicmd.emacs-mcx.killSexp",
        "when": "editorTextFocus && !editorReadonly"
}

**Comment by whitphx** [comment]
Setting mark with yank and exiting i-search has been supported by the extension from version 0.27.0 👍 

Regardless of that, thank you for sharing the knowledge of using multi-command, with which we can have more customizing capability :)
