### ISSUE TITLE
Can't search with case-sensitivity

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [whitphx/vscode-emacs-mcx#409]
I cannot search case-sensitive.

Thanks you so much.

**Comment by tuttieee** [comment]
Is the VSCode's native `Match Case` functionality sufficient?
https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options

If you want the original Emacs' a little bit complicated behavior referred below, I think it's not worth implementing it within this extension, sorry. This extension simply owes VSCode's native searching functionality.

> When the search string contains only lower case letters, the search ignores case, but when the search string contains one or more upper case letters, the search becomes case-sensitive. 

(Ref: https://www.gnu.org/software/emacs/manual/html_node/elisp/Searching-and-Case.html )

**Comment by tuttieee** [comment]
Or does it help if there is a keybinding to toggle case-sensitivity during i-search?

**Comment by HidenoriMatsubayashi** [comment]
The default behavior of emacs seems to be that if the search string contains at least one uppercase letter, it will search case-sensitively. On the other hand,  if the search string is all lowercase, it is not case sensitive. Is it difficult to imitate this behavior?

**Comment by tuttieee** [comment]
It cannot be done by VSCode's native search functionality then have to be implemented in the extension itself.
For example, it seems [VSCodeVim](https://github.com/VSCodeVim/Vim) has its own search implementation to simulate the original Vim's behavior (though I haven't used and tested it).
However, now I can't pay efforts for it soon.
I will keep this issue open and be open to discuss.

Of course, PRs to this extension are so much welcome.
Another option is to create a new extension just for it.
I think the case-sensitive search is an independent functionality unrelated to Awesome Emacs Keymap's other methods. Then, it can be another independent extension.

**Comment by HidenoriMatsubayashi** [comment]
OK. Thank you so much.
