### ISSUE TITLE
Version conflicts with 1.49.3

### ISSUE THREAD

**Issue by truesilver92** [whitphx/vscode-emacs-mcx#519]
I am using the nixOS vscodium release of this project (version 1.49.3). I also tried using the manjaro release 1.49.1 I could not install the newest version of this extension or any of the versions on the market place. The only release that exists+works is the v0.23.0-dev0 release (please add releases for each version to at least github and/or fix the market place to hold onto versions for previous vscode releases)

**Comment by tuttieee** [comment]
I found you can download VSIX files of older versions of this extension from the market place by specifying the link to
`https://marketplace.visualstudio.com/_apis/public/gallery/publishers/tuttieee/vsextensions/emacs-mcx/${VERSION}/vspackage`.
For example, you can download v0.22.0 from https://marketplace.visualstudio.com/_apis/public/gallery/publishers/tuttieee/vsextensions/emacs-mcx/0.22.0/vspackage
though it's not shown in [the version history page in the marketplace](https://marketplace.visualstudio.com/items?itemName=tuttieee.emacs-mcx&ssr=false#version-history)

For example, v0.22.4 is compatible with `vscode@^1.49.0`: https://github.com/tuttieee/vscode-emacs-mcx/blob/029a89705705024ea2f864f634632bd127e824e2/package.json#L12

**Comment by truesilver92** [comment]
Thank you. This is good to know
