### ISSUE TITLE
emacs-mcx commands not showing up in command palette

### ISSUE THREAD

**Issue by samwagg** [whitphx/vscode-emacs-mcx#550]
It looks to me that commands created by this extension do not appear in the command palette.  I think there needs to be a "commands" section added to the "contributes" map in package.json where all the commands can be registered. This is documented here: https://code.visualstudio.com/api/extension-guides/command#creating-a-user-facing-command

I would be happy to open a PR for this if desired. It is important for me (and I suspect others) to be able to look up commands using the palette.

**Comment by tuttieee** [comment]
Thank you for the suggestion. I will consider it.

**Comment by whitphx** [comment]
@samwagg Sorry for long-delayed reply.

> I would be happy to open a PR for this if desired. 

Please do it if you are still available.
