### ISSUE TITLE
sexp delimiters should be language specific

### ISSUE THREAD

**Issue by samwagg** [whitphx/vscode-emacs-mcx#551]
I see that the paredit library seems to hardcode them. https://github.com/rksm/paredit.js/blob/master/lib/reader.js#L26, so I guess it's not a trivial change. I think it's important though.

My motivating example is that I want HTML and JSX expressions to be treated as balanced expressions when appropriate.

**Comment by tuttieee** [comment]
mm, all you said is right.
It would be useful, but difficult to implement due to the hardcoded delimiters...
I will consider how to do it.
If necessary, forking and modifying paredit.js can be an option.
