### ISSUE TITLE
Prefix arguments don't work completely

### ISSUE THREAD

**Issue by jhannwong** [whitphx/vscode-emacs-mcx#594]
Maybe I'm having some overriding shortcuts in VSCode that prevents prefix arguments from working?

I can't get prefix arguments to work according to [this specification](https://www.gnu.org/software/emacs/manual/html_node/emacs/Arguments.html).

**Comment by tuttieee** [comment]
Which keybindings do not work?
This extension is not supporting `M-<number>` and `M--` keybindings as README describes.
