### ISSUE TITLE
M-b (Move backward by one word unit (backward-word)) seems to not do anything on macOS

### ISSUE THREAD

**Issue by nottoseethesun** [whitphx/vscode-emacs-mcx#603]
I'm on VSCode Version: 1.52.1 , on macOS Big Sur, with this emacs keybindings extension being the only emacs-related extension installed.

Afaik, I have no other extensions that touch M-b ("option key"-b on macOS).

**Comment by whitphx** [comment]
mm, I cannot reproduce it in my environment.

Please follow https://github.com/whitphx/vscode-emacs-mcx/issues/142#issuecomment-544151239 to check `M-b` assignment on your environment and report the result again.

**Comment by nottoseethesun** [comment]
Checked it and `[option-key] b` (above, I had incorrectly written `-b`) still doesn't work:

`~/Library/Application Support/Code/User/keybindings.json` 

```
  {
    "key": "alt+b",
    "command": "emacs-mcx.backwardWord",
    "when": "config.emacs-mcx.useMetaPrefixEscape && editorTextFocus"
  },
  {
    "key": "escape b",
    "command": "-emacs-mcx.backwardWord",
    "when": "config.emacs-mcx.useMetaPrefixEscape && editorTextFocus"
  },
  {
    "key": "b",
    "command": "emacs-mcx.backwardWord",
    "when": "editorTextFocus && !config.emacs-mcx.useMetaPrefixMacCmd"
  },
  {
    "key": "alt+b",
    "command": "-emacs-mcx.backwardWord",
    "when": "editorTextFocus && !config.emacs-mcx.useMetaPrefixMacCmd"
  },
```

**Comment by nottoseethesun** [comment]
Looks like the `-` character in `"-emacs-mcx.backwardWord"` made the difference:

```  
{
    "key": "escape b",
    "command": "-emacs-mcx.backwardWord",
    "when": "config.emacs-mcx.useMetaPrefixEscape && editorTextFocus"
  },
```
