### ISSUE TITLE
shortcut invalid in search box

### ISSUE THREAD

**Issue by ColorFuzzy** [whitphx/vscode-emacs-mcx#632]
![image](https://user-images.githubusercontent.com/1814478/104693871-52e48500-5745-11eb-8563-d59e50b3edf3.png)

In the replace widget, when focusing the first widget(search text) `ctrl-a` makes the search box disappear when focusing the second widget(replace text), `ctrl-a` moves the cursor to the beginning. Why such a difference, can I make `ctrl-a` works in the first widget?

**Comment by whitphx** [comment]
See #271 and #360
