### ISSUE TITLE
garbage in quickOpen box 

### ISSUE THREAD

**Issue by yuzhichang** [whitphx/vscode-emacs-mcx#644]
When I type `ctrl+x b`, the quickOpen box content is `etd mru `. I have to delete them before input what I need. It's an minor annoyance.

**Comment by whitphx** [comment]
It's not garbage. See the difference between `C-x C-f` (`workbench.action.quickOpen`, emulating Emacs' `find-file`) and `C-x b` (`workbench.action.showAllEditorsByMostRecentlyUsed`, emulating Emacs' `switch-to-buffer`).
See also #289.

If you are still uncomfortable with it, you can change the configuration on your environment by editing your `keybindings.json`.

**Comment by yuzhichang** [comment]
I see. Thanks!
