### ISSUE TITLE
the shortcut is frozen for about 10 seconds after reload window 

### ISSUE THREAD

**Issue by ColorFuzzy** [whitphx/vscode-emacs-mcx#647]
With this extension enabled, the shortcut is frozen(`ctrl-a/b/e/f/n/p` in macOS) for about 10 seconds after reloading the window, this was figured out with `extension bisect`.

**Comment by whitphx** [comment]
Thank you for reporting.
Does it mean only this extension takes much longer time for initialization than other extensions?

**Comment by ColorFuzzy** [comment]
> Thank you for reporting.
> Does it mean only this extension takes a much longer time for initialization than other extensions?

I have about 122 extensions, they all take time to initialization, but only this extension block my editing after startup, I have to wait this extension if I want to move the cursor by keyboard(the mouse is not blocked).

**Comment by whitphx** [comment]
#1720 might solve this?
If this problem still exists with the latest version of the extension, plz report it and reopen this issue.
