### ISSUE TITLE
Search (e.g. ctrl-S) forgets search string and cannot repeat search

### ISSUE THREAD

**Issue by nickion** [whitphx/vscode-emacs-mcx#682]
Search, e.g. ctrl-S, works fine when starting a search, however after editing at a search location the search string is forgotten. Doing a new ctrl-S search will initiate a fresh search string taken from neighbouring context rather than redoing a search with the previous search string as emacs would.

Although there is F3 to do a repeat search, an option for ctrl-S to use the previous search string would be nice. Search would then initialise the search from buffer contents only if text is selected, although to be even more emacs compliant, it would also be nice to be able to disable that.

**Comment by whitphx** [comment]
See #107 for the workaround.

In addition,
> an option for ctrl-S to use the previous search string would be nice.

this  is true, but still there seems not to be such an option.

**Comment by nickion** [comment]
> See #107 for the workaround.

Thanks and sorry for duplicate; I did skim through the issues but didn't spot it.
