### ISSUE TITLE
Question: Why is C-x C-c not bound to "Close Window" by default?

### ISSUE THREAD

**Issue by stewSquared** [whitphx/vscode-emacs-mcx#731]
Perhaps this is a bit of a frivolous question, but I found it surprising, since it's such a basic command.

Yes, I did figure out that I can just `C-x C-k C-w` or `M-x close window`, but that's beside the point.

**Comment by whitphx** [comment]
No reason. `C-x C-c` has not been intentionally omitted, but just not been taken care of.
I will add the keybinding, thank you.
