### ISSUE TITLE
Viewport does not follow cursor with forwardParagraph/backwardParagraph in mark mode

### ISSUE THREAD

**Issue by joeshaw** [whitphx/vscode-emacs-mcx#758]
Observe how the viewport moves as you use C-up and C-down to jump backward and forward by paragraphs.

Now activate mark mode (C-space) and do the same thing.  The viewport stays at its initial location.  I can get things to jump to the right place by using a different navigation key, like left or right arrow by itself.

It doesn't seem to happen 100% of the time, but I haven't been able to find out a good heuristic for when it does.  But it does happen most of the time for me.

**Comment by whitphx** [comment]
Thank you for the report!
I have reproduced this problem and fixed it via #766 , which will be in the next release.
