### ISSUE TITLE
Feature request, alt+w copy the content in the pop-up document

### ISSUE THREAD

**Issue by kekeimiku** [whitphx/vscode-emacs-mcx#771]
# e.g
# alt-w copy selected part
## I tried to set `editor.action.clipboardCopyAction` to `alt-w`, but this caused the setmark to fail to be automatically cancelled. I don't know what to do next, I don’t know anything about typescript, I hope you can help me.
![image](https://user-images.githubusercontent.com/36557882/115057935-39ef9980-9f17-11eb-85e4-d1cb83ac3a83.png)
![image](https://user-images.githubusercontent.com/36557882/115058041-60153980-9f17-11eb-9de4-411bdce2f34e.png)

**Comment by whitphx** [comment]
I think it's impossible because the pop up is OS native UI and VSCode cannot set keybindings on native UIs.
Similar to #137
