### ISSUE TITLE
Arrow key closes Find dialog

### ISSUE THREAD

**Issue by ttrace** [whitphx/vscode-emacs-mcx#905]
With enabling vscode-emacs-mcx, arrow keys (and all the other cursor position controls) moves cursor on Editor even if  Menu > Edit > Find dialog opens (and closes Find dialog).

Users can't edit text in Find dialog with moving cursor.

**Comment by whitphx** [comment]
It's an intended behavior.
See https://github.com/whitphx/vscode-emacs-mcx/issues/137 for the background and related discussions including an option to disable it.

**Comment by ttrace** [comment]
I got, thanks.
