### ISSUE TITLE
setMarkCommand resets with "Go to bracket"

### ISSUE THREAD

**Issue by zpencer** [whitphx/vscode-emacs-mcx#921]
"Go to bracket" takes you from a bracket / brace / paren to the matching counterpart.

When I hit ctrl-space and navigate to a bracket / brace / paren, and then run the shortcut for "Go to bracket", the expected behavior is that the marked region includes everything in the matching brackets.

However, what actually happens is that as soon as "Go to bracket" is run, the marked region becomes unselected.

**Comment by whitphx** [comment]
It's because the mark mode is only managed within this extension and any commands provided by VSCode or other extensions do not take care of it.
Use [the sexp commands](https://github.com/whitphx/vscode-emacs-mcx#sexp) of this extension to deal with brackets in a way compatible with the mark mode.
