### ISSUE TITLE
a workaround to emulate emacs edit rectangle `ctrl-x-r-t` with repeatedly replace one line in killring to rectangle

### ISSUE THREAD

**Issue by shengofsun** [whitphx/vscode-emacs-mcx#924]
I love this extension very much, but I found `ctrl-x-r-t` hasn't supported yet. after reading the code, I guess it's a bit hard to implement due to the limitation of vscode. 

so I'm wondering whether we can emulate this by copy lines from the killring, and I try to implement this with this pull request: #923 

I've tried this on my own, and I think it works well if we want to edit something in a rectangle. but i'm not sure whether it breaks the project's design and so that a discussion may be necessary.

**Comment by whitphx** [comment]
Thank you for the suggestion and contribution.
It seems adding this command does not conflict with others and does not breaks the project design as you followed the current project structure and properly isolated the implementation inside a single command class. Very helpful.

Honestly I'm not an active user of `C-x r t` and cannot judge `C-x r p` you suggested, so I'm open to merge it as you say it's convenient :)

**Comment by shengofsun** [comment]
merged in #923
