### ISSUE TITLE
support Visual Studio Code Web

### ISSUE THREAD

**Issue by limon** [whitphx/vscode-emacs-mcx#962]
As Github provides this feature: https://twitter.com/github/status/1425505817827151872
Will this extension support Visual Studio Code Web?

**Comment by whitphx** [comment]
It seems not to have been documented yet about how to make the extension compatible with web-based VSCode.

https://github.com/microsoft/vscode/issues/111043 is a hint.
I added `"web"` to `"extensionKind"` field in `package.json` and released it in v0.33.2, which can be installed to VSCode Web, but still does not work with different errors.

**Comment by whitphx** [comment]
`"browser"` field also seems to be necessary
https://github.com/VSCodeVim/Vim/commit/b774b99b937ef18e826399b96c2622e60e7051a0

**Comment by whitphx** [comment]
This is discussed in the VSCode official repo and they said it will be documented:
https://github.com/microsoft/vscode/issues/130628#issuecomment-897705052

I will wait for it and pend this issue until that.

**Comment by whitphx** [comment]
Released with 0.34.0
