### ISSUE TITLE
Feature request: shortcut to create and open a new file

### ISSUE THREAD

**Issue by kekeimiku** [whitphx/vscode-emacs-mcx#964]
I hope I can use c-x c-f to create and open new files like emacs

**Comment by kekeimiku** [comment]
I found this as an alternative  https://github.com/bodil/vscode-file-browser
edit keybindings.json to add
```json
{
        "key": "ctrl+x ctrl+f",
        "command": "file-browser.open"
},
```

**Comment by whitphx** [comment]
Thanks, I updated the README to refer to the extension: https://github.com/whitphx/vscode-emacs-mcx/pull/1184
